id: P001707
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ62374
  title: གསུང་འབུམ། དབྲ་སྟོན་ངག་དབང་བསྐལ་བཟང་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  volumes:
    0cef9304cd40402a9dfdaae33f79ef19:
      image_group_id: I4CZ62376
      title: ''
      volume_number: 1
      total_pages: 560
      base_file: v001.txt
    2a71f63c5a754da89a769d8994493585:
      image_group_id: I4CZ62377
      title: ''
      volume_number: 2
      total_pages: 586
      base_file: v002.txt
    d4da8f4336164a5eafe57a36b76ae1c5:
      image_group_id: I4CZ62378
      title: ''
      volume_number: 3
      total_pages: 580
      base_file: v003.txt
    36ebda757b3447c994c33354ee7b2306:
      image_group_id: I4CZ62379
      title: ''
      volume_number: 4
      total_pages: 548
      base_file: v004.txt
    156379724c36488da002d3087c9e501e:
      image_group_id: I4CZ62380
      title: ''
      volume_number: 5
      total_pages: 566
      base_file: v005.txt
    1b46279493b6401e9de5c03f8bba99d6:
      image_group_id: I4CZ62381
      title: ''
      volume_number: 6
      total_pages: 568
      base_file: v006.txt
    d1f2d40d90c740c196ab96dceb9633a3:
      image_group_id: I4CZ62382
      title: ''
      volume_number: 7
      total_pages: 504
      base_file: v007.txt
    99267b7b8086412f9906c2b0ea2e2da7:
      image_group_id: I4CZ62383
      title: ''
      volume_number: 8
      total_pages: 516
      base_file: v008.txt
