id: I1C6BF660
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:59:50+00:00'
last_modified: '2022-06-07T14:52:03.460612+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ62374
  title: གསུང་འབུམ། དབྲ་སྟོན་ངག་དབང་བསྐལ་བཟང་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7F57:
      image_group_id: I4CZ62376
      title: ''
      total_pages: 560
      order: 1
      base_file: 7F57.txt
    9B6B:
      image_group_id: I4CZ62377
      title: ''
      total_pages: 586
      order: 2
      base_file: 9B6B.txt
    '9146':
      image_group_id: I4CZ62378
      title: ''
      total_pages: 580
      order: 3
      base_file: 9146.txt
    1D3F:
      image_group_id: I4CZ62379
      title: ''
      total_pages: 548
      order: 4
      base_file: 1D3F.txt
    F2C6:
      image_group_id: I4CZ62380
      title: ''
      total_pages: 566
      order: 5
      base_file: F2C6.txt
    75E8:
      image_group_id: I4CZ62381
      title: ''
      total_pages: 568
      order: 6
      base_file: 75E8.txt
    AFAD:
      image_group_id: I4CZ62382
      title: ''
      total_pages: 504
      order: 7
      base_file: AFAD.txt
    74CC:
      image_group_id: I4CZ62383
      title: ''
      total_pages: 516
      order: 8
      base_file: 74CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
